import { IconCard } from "@/components/mdx/icon-card";
import { Mermaid } from "@/components/mdx/mermaid";
import { ImageZoom } from "fumadocs-ui/components/image-zoom";
import * as TabsComponents from "fumadocs-ui/components/tabs";
import { Step, Steps } from "fumadocs-ui/components/steps";
import { Accordion, Accordions } from "fumadocs-ui/components/accordion";
import { Callout } from "fumadocs-ui/components/callout";
import { TypeTable } from "fumadocs-ui/components/type-table";
import { File, Folder, Files } from "fumadocs-ui/components/files";
import { Card, Cards } from "fumadocs-ui/components/card";
import defaultMdxComponents from "fumadocs-ui/mdx";
import type { MDXComponents } from "mdx/types";

// Carbon manual UI components (render real demo data as faithful app mockups)
import { AppShot } from "@/components/manual/app-shot";
import { DataTable } from "@/components/manual/data-table";
import { RecordPanel, FieldGrid, Field } from "@/components/manual/record";
import { MethodTree } from "@/components/manual/method-tree";
import { StatusBadge, Tag } from "@/components/manual/badge";
import { Stat, StatGrid } from "@/components/manual/stats";
import { CarbonShell } from "@/components/manual/shell";

import {
  Activity,
  Ban,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Box,
  Boxes,
  BrainCog,
  Building2,
  Calculator,
  Check,
  CircleCheck,
  CirclePlay,
  ClipboardCheck,
  ClipboardList,
  Cloud,
  Cog,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  EyeOff,
  Factory,
  FileText,
  Gauge,
  GitMerge,
  Hammer,
  KeyRound,
  Layers,
  LineChart,
  Lock,
  Map,
  Package,
  PackageCheck,
  Plug,
  Receipt,
  Rocket,
  Ruler,
  Scan,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Tags,
  Truck,
  Upload,
  Users,
  Warehouse,
  Workflow,
  Wrench,
  Zap,
  Building,
  Code,
  Compass,
  Globe,
  ListChecks,
  PlayCircle,
  RefreshCw,
} from "lucide-react";
import { SiPython, SiTypescript } from "react-icons/si";

// use this function to get MDX components, you will need it for rendering MDX
export function getMDXComponents(components?: MDXComponents): MDXComponents {
  return {
    ...defaultMdxComponents,
    // Fumadocs building blocks
    Mermaid,
    IconCard,
    Card,
    Cards,
    Step,
    Steps,
    Accordion,
    Accordions,
    Callout,
    TypeTable,
    File,
    Folder,
    Files,
    // Carbon manual UI kit
    AppShot,
    DataTable,
    RecordPanel,
    FieldGrid,
    Field,
    MethodTree,
    StatusBadge,
    Tag,
    Stat,
    StatGrid,
    CarbonShell,
    // Lucide icons (for IconCard / inline use)
    Activity,
    Ban,
    BarChart3,
    Bell,
    BookOpen,
    Bot,
    Box,
    Boxes,
    BrainCog,
    Building2,
    Calculator,
    Check,
    CircleCheck,
    CirclePlay,
    ClipboardCheck,
    ClipboardList,
    Cloud,
    Cog,
    Cpu,
    CreditCard,
    Database,
    DollarSign,
    EyeOff,
    Factory,
    FileText,
    Gauge,
    GitMerge,
    Hammer,
    KeyRound,
    Layers,
    LineChart,
    Lock,
    Map,
    Package,
    PackageCheck,
    Plug,
    Receipt,
    Rocket,
    Ruler,
    Scan,
    Server,
    Settings,
    Shield,
    ShieldCheck,
    ShoppingCart,
    Tags,
    Truck,
    Upload,
    Users,
    Warehouse,
    Workflow,
    Wrench,
    Zap,
    Building,
    Code,
    Compass,
    Globe,
    ListChecks,
    PlayCircle,
    RefreshCw,
    TypeScriptIcon: SiTypescript,
    PythonIcon: SiPython,
    img: (props) => <ImageZoom {...(props as any)} />,
    ...TabsComponents,
    ...components,
  };
}
